[package]
name = "knaster"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["knaster_graph/std"]
unstable = ["knaster_graph/unstable"]

[dependencies]
knaster_graph = { path = "../knaster_graph/" }
