name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: knaster tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libgtk-3-dev
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - uses: extractions/setup-just@v3
      - name: Build
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

        run: cargo build --verbose --features=std,cpal,jack
      - name: Run tests
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: just test-all
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri

  miri-tests:
    name: knaster tests - miri
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libgtk-3-dev
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: extractions/setup-just@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - name: Run knaster_graph tests through miri
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: cd knaster_graph && cargo +nightly miri test --verbose
      - name: Run knaster_core tests through miri
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        run: cd knaster_core && cargo +nightly miri test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
