name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: knaster tests - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - name: Install dependencies
      run: sudo apt-get install libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libgtk-3-dev 
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    - name: Configure sccache
      uses: visvirial/sccache-action@v1
      with:
        # Optional
        cache-key: sccache-ubuntu-latest
        # Optional
        release-name: latest
        # Optional
        arch: x86_64-unknown-linux-musl
    - uses: extractions/setup-just@v3
    - name: Build
      run: cargo build --verbose --features=cpal,jack,serde-derive 
    - name: Run tests
      run: just test-all
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: miri
    - name: Run tests through miri
      run: cargo +nightly miri test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
